version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: "payroll-challenge-api/Dockerfile"
    ports:
      - "8080:80"
    environment:
      ConnectionStrings__EmployeeContext: "Host=host.docker.internal;Port=5432;Database=${POSTGRES_DATABASE};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}"
      FrontendOrigin: "http://localhost:3000"
    depends_on:
      - database
        
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "9000:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "brmatola@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "password"
    depends_on:
      - database

  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DATABASE}"
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      
networks:
  backend:
    driver: bridge
      