version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: "payroll-challenge-api/Dockerfile"
    ports:
      - "8080:80"
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "secret_password123"
      ACCEPT_EULA: "Y"
      