name: 'Build'

on:
  push:
    branches:
      - main
    pull_request:

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Test
        working-directory: ./src
        run: dotnet test